language: java

dist: trusty

jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "comdevonfw"
    token:
      secure: "L+eRjJMYpmMAYYQV0UA5KNhzMXAxS48+++45lEBbibVhINNBUMUuUm+7fC93VGbkDKWpI
              XbS7y54sYlCafISA1zrOZKbhyFxADmkiPx5Dl4M9PRN0ufnTsyA4MFUSOY0sciIsz46pe0Y6bPhSjpGk
              XbPQRyCePhu7BKxOVio8G7dmHLScsICJQh2ciK/SgnKjkJlEDPtFCR97WLtsnNnwd6BXjyRWNPpmAI4H
              nkTuGPXtOEHM2uzvqT+aOEUWDZrcasweL2e5bPehHDgyZyDFuAjsOr670xECB+71ZfUzOLxq9Fq5aW+c
              pKbW3aPtKrGNcS6NEbqghe53ugYq0TyXHurBAQbGP1aotYf1KdJ3uKpTm3LcmoTtSi7TX4rbPh7tvhpn
              bm91keJG6MjQIh86NTYU2zvgw2h4+pHFl5MUfecuVfidWFCYO5PLJ+3q2gEchWbiuH9Q0W1Sf8E398Zx
              bmzvaOGb+edIAejl3PNJfSgnFzx+lXo9zbH0/J1filNhjIrjcZFywB7jIZJRxdNZc4eJdSMZ4iUTT/ys
              mrEWuFiBKZkS3X4MPZgBQN+SAJRFAo3V7ekwuhVEO3dQcTtttynux+Jd2Hl+sdaYeipoygmBuNRpW69i
              OzE0lBZ2n6Gga7M0dJMoo8Z1lGKQKfVGHC3yPpKoa59TXslTOJE1kI="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=devonfw_sonar-devon4j-plugin -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=comdevonfw

sudo: false

cache:
  directories:
    - $HOME/.m2

branches:
  except:
    - gh-pages

notifications:
  email:
    - joerg.hohwiller@googlemail.com
