# This is a basic workflow to help you get started with Actions
name: sonarcloud
env:
  ORG: "comdevonfw"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 # Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
jobs:
  build:
        name: checking codition
        if: ${{github.repository == 'devonfw/sonar-devon4j-plugin'}}
        runs-on: ubuntu-latest
        steps:
             - name: Checkout code
               uses: actions/checkout@v2   
             - name: Set up JDK 11.0.10
               uses: actions/setup-java@v1
               with:
               java-version: 11.0.10
             - name: build the project with Maven     
                run: |
                mvn clean -Pjacoco-report install sonar:sonar -Dsonar.projectKey=devonfw_sonar-devon4j-plugin -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=comdevonfw;
             - name: build the project with Maven
               run : mvn clean install
  

    
