name: sonarcloud
env:
  ORG: "comdevonfw"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches:  master 
jobs:
       build:
        if: ${{github.repository == 'devonfw/sonar-devon4j-plugin'}}
        runs-on: ubuntu-latest
        steps:
             - name: Set up JDK
               uses: actions/setup-java@v1
               with:
                java-version: '8'
             - name: build the project with Maven     
               run:
                   mvn clean -Pjacoco-report install sonar:sonar -Dsonar.projectKey=devonfw_sonar-devon4j-plugin -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=comdevonfw;
             
  

    
