name: sonarcloud
env:
  ORG: "comdevonfw"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches:  master 
jobs:
       build:
        runs-on: ubuntu-latest
        if: ${{github.event.repository =='devonfw/sonar-devon4j-plugin'}}
        steps:
             - name: Checkout code
               uses: actions/checkout@v2   
             - name: Set up JDK
               uses: actions/setup-java@v1
               with:
                java-version: '11'
             - name: build the project with Maven     
               run:
                   mvn clean -Pjacoco-report install sonar:sonar -Dsonar.projectKey=devonfw_sonar-devon4j-plugin -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=comdevonfw;
             
  

    
